name: SAM CD

on:
   push:
    branches:
      - master


jobs:
  Release_CD:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: sudo apt install python3-pip
      - run: pip3 install --upgrade setuptools
      - run: pip3 install -U awscli
      - run: aws configure set aws_access_key_id ${{secrets.AWS_ACCESS_KEY_ID}}
      - run: aws configure set aws_secret_access_key ${{secrets.AWS_SECRET_TOKEN}}
      - run: pip3 install -U aws-sam-cli
      - run: (cd get-views/ && npm ci)
      - run: sam build
      - run: sam deploy --no-confirm-changeset
      - run:  | 
          aws dynamodb put-item --table-name ResumeViewsTable --item '{"id": {"S": "subham_resume"}, "views": {"N": "1"}}'
